@extends('layouts.dashboard')

@section('title', 'Claim Pass')

@section('content')

@php
    $claimPassStatus = 'Pending Review';
    $claimGuidanceTitle = 'Awaiting Approval';
    $claimGuidanceCopy = 'Your assistance request is still under review. A QR/reference pass will appear after approval.';
    $claimGuidanceClasses = 'border-amber-200 bg-amber-50 text-amber-800';

    if ($claim->status === 'Rejected') {
        $claimPassStatus = 'Rejected';
        $claimGuidanceTitle = 'Request Rejected';
        $claimGuidanceCopy = 'This assistance request was not approved. You may submit another request for an available program.';
        $claimGuidanceClasses = 'border-rose-200 bg-rose-50 text-rose-800';
    } elseif ($claim->is_claimed) {
        $claimPassStatus = 'Claimed';
        $claimGuidanceTitle = 'Claim Processed';
        $claimGuidanceCopy = 'This claim pass has already been validated and processed by a merchant.';
        $claimGuidanceClasses = 'border-cyan-200 bg-cyan-50 text-cyan-800';
    } elseif ($claim->status === 'Approved' && $claim->expiration_date && now()->greaterThan($claim->expiration_date)) {
        $claimPassStatus = 'Expired';
        $claimGuidanceTitle = 'Claim Pass Expired';
        $claimGuidanceCopy = 'This approved claim pass is past its validity date and may no longer be accepted.';
        $claimGuidanceClasses = 'border-slate-200 bg-slate-50 text-slate-700';
    } elseif ($claim->status === 'Approved') {
        $claimPassStatus = 'Valid Claim Pass';
        $claimGuidanceTitle = 'Claim Ready';
        $claimGuidanceCopy = 'Present this claim QR or reference code to an accredited merchant to validate your approved assistance.';
        $claimGuidanceClasses = 'border-emerald-200 bg-emerald-50 text-emerald-800';
    }
@endphp

<div class="w-full min-w-0 max-w-5xl space-y-6 print-pass">
    <x-page-header
        class="print:hidden"
        title="Claim Pass"
        eyebrow="Digital Claim Pass"
        description="Present this authorization and validation pass to an accredited merchant for assistance claim validation.">
        <x-slot:actions>
        <a href="{{ route('member.claims.index') }}"
           class="inline-flex min-h-11 w-full items-center justify-center rounded-xl border border-ui-border bg-white px-5 py-3 text-sm font-semibold text-slate-700 transition hover:bg-ui-canvas sm:w-fit">
            Back to My Claims
        </a>
        </x-slot:actions>
    </x-page-header>

    <div class="grid grid-cols-1 gap-6 xl:grid-cols-3">

        <div class="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm xl:col-span-2">

            <div class="border-b border-slate-100 p-5 sm:p-8">
                <div class="flex flex-wrap items-start justify-between gap-4">
                    <div class="min-w-0">
                        <p class="text-sm font-semibold uppercase tracking-wider text-slate-500">
                            Assistance Program
                        </p>

                        <h2 class="mt-2 break-words text-2xl font-bold text-slate-800">
                            {{ $claim->program->program_name }}
                        </h2>

                        <p class="mt-2 text-slate-500">
                            Claim reference generated by EduNexUs after cooperative approval.
                        </p>
                    </div>

                    <x-status-badge :status="$claimPassStatus" :tone="$claimPassStatus" size="xs" />
                </div>
            </div>

            <div class="grid grid-cols-1 gap-4 border-b border-slate-100 p-5 sm:p-8 md:grid-cols-2">
                <div class="rounded-2xl border border-slate-100 bg-slate-50 p-4">
                    <p class="text-sm text-slate-500">
                        Approved Amount
                    </p>

                    <p class="mt-1 font-semibold text-slate-800">
                        ₱{{ number_format($claim->approved_amount ?? $claim->requested_amount, 2) }}
                    </p>
                </div>

                <div class="rounded-2xl border border-slate-100 bg-slate-50 p-4">
                    <p class="text-sm text-slate-500">
                        Expiration Date
                    </p>

                    <p class="mt-1 font-semibold text-slate-800">
                        {{ $claim->expiration_date?->format('M d, Y') ?? 'Not available' }}
                    </p>
                </div>

                <div class="rounded-2xl border border-slate-100 bg-slate-50 p-4">
                    <p class="text-sm text-slate-500">
                        Reference Code
                    </p>

                    <p class="mt-2 block break-all rounded-xl border border-slate-200 bg-white px-4 py-3 font-mono text-sm font-semibold text-slate-800">
                        {{ $claim->reference_code ?? 'Pending approval' }}
                    </p>
                </div>

                <div class="rounded-2xl border border-slate-100 bg-slate-50 p-4">
                    <p class="text-sm text-slate-500">
                        Claim Status
                    </p>

                    <p class="mt-1 font-semibold text-slate-800">
                        {{ $claim->is_claimed ? 'Already claimed at merchant' : ($claim->status === 'Approved' ? 'Ready for merchant validation' : $claim->status) }}
                    </p>
                </div>
            </div>

            <div class="p-5 sm:p-8">
                <div class="rounded-2xl border p-5 {{ $claimGuidanceClasses }}">
                    <p class="font-semibold">
                        {{ $claimGuidanceTitle }}
                    </p>

                    <p class="mt-1 text-sm">
                        {{ $claimGuidanceCopy }}
                    </p>
                </div>
            </div>
        </div>

        <div class="flex min-w-0 flex-col items-center space-y-6">
            <div class="mx-auto w-full max-w-[20rem] rounded-2xl border border-slate-200 bg-white p-5 text-center shadow-sm">
                <p class="text-sm font-semibold text-slate-700">
                    QR Claim Pass
                </p>

                <p class="mt-1 text-sm text-slate-500">
                    Authorization pass for merchant validation.
                </p>

                @if($claim->qr_code)
                    <div class="mx-auto mt-5 flex w-full max-w-[17rem] justify-center">
                        <div class="qr-pass-frame inline-flex max-w-full justify-center rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:p-4">
                            {!! \SimpleSoftwareIO\QrCode\Facades\QrCode::size(220)->generate($claim->qr_code) !!}
                        </div>
                    </div>

                    <p class="mt-4 text-xs text-slate-400">
                        QR is linked to your approved claim reference.
                    </p>

                    <button type="button"
                            id="open-qr-modal"
                            class="print:hidden mt-5 w-full rounded-xl border border-teal-200 bg-teal-50 px-5 py-3 font-semibold text-teal-700 transition hover:border-teal-300 hover:bg-teal-100">
                        Enlarge QR
                    </button>

                    <button onclick="window.print()"
                            class="print:hidden mt-3 w-full rounded-xl bg-teal-600 px-5 py-3 font-semibold text-white transition hover:bg-teal-700">
                        Print Claim Pass
                    </button>
                @else
                    <div class="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-left">
                        <p class="font-semibold text-amber-800">
                            QR not available
                        </p>

                        <p class="mt-1 text-sm text-amber-700">
                            QR code will appear after approval.
                        </p>
                    </div>
                @endif
            </div>

            <div class="mx-auto w-full max-w-[20rem] rounded-2xl border border-teal-100 bg-teal-50 p-5">
                <p class="text-sm font-semibold text-teal-800">
                    Important Reminder
                </p>

                <p class="mt-2 text-sm text-teal-700">
                    Each approved claim can only be redeemed once. Claims are validated through EduNexUs before merchant processing.
                </p>
            </div>
        </div>

    </div>

</div>

@if($claim->qr_code)
    <div id="qr-modal"
         class="fixed inset-0 z-50 hidden items-center justify-center overflow-hidden px-4 py-4 print:hidden"
         role="dialog"
         aria-modal="true"
         aria-labelledby="qr-modal-title">
        <div id="qr-modal-backdrop"
             class="absolute inset-0 bg-slate-950/60 backdrop-blur-sm"></div>

        <div id="qr-modal-panel"
             class="relative flex max-h-[calc(100vh-2rem)] w-full max-w-md translate-y-3 scale-[0.98] flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white p-4 opacity-0 shadow-2xl transition duration-200 ease-out sm:max-w-lg sm:p-6">
            <div class="flex shrink-0 items-start justify-between gap-4">
                <div class="min-w-0">
                    <p class="text-xs font-semibold uppercase tracking-wider text-teal-700 sm:text-sm">
                        Merchant Presentation
                    </p>

                    <h2 id="qr-modal-title"
                        class="mt-1 text-xl font-bold text-slate-800 sm:mt-2 sm:text-2xl">
                        Enlarge QR
                    </h2>

                    <p class="mt-1 text-sm text-slate-500">
                        Present this authorization pass at the merchant validation terminal.
                    </p>
                </div>

                <button type="button"
                        id="close-qr-modal"
                        class="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-slate-200 text-slate-500 transition hover:bg-slate-50 hover:text-slate-700"
                        aria-label="Close QR modal">
                    <x-icon name="x" size="h-5 w-5" />
                </button>
            </div>

            <div class="mt-4 min-h-0 flex-1 overflow-hidden rounded-2xl border border-slate-200 bg-slate-50 p-4 text-center sm:mt-5 sm:p-5">
                <div class="qr-pass-frame inline-flex max-w-full justify-center rounded-2xl border border-slate-200 bg-white p-3 shadow-sm">
                    <div class="sm:hidden">
                        {!! \SimpleSoftwareIO\QrCode\Facades\QrCode::size(220)->generate($claim->qr_code) !!}
                    </div>

                    <div class="hidden sm:block lg:hidden">
                        {!! \SimpleSoftwareIO\QrCode\Facades\QrCode::size(260)->generate($claim->qr_code) !!}
                    </div>

                    <div class="hidden lg:block">
                        {!! \SimpleSoftwareIO\QrCode\Facades\QrCode::size(300)->generate($claim->qr_code) !!}
                    </div>
                </div>

                <p class="mt-3 text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Reference Code
                </p>

                <p class="mt-2 break-all rounded-xl border border-slate-200 bg-white px-3 py-2 font-mono text-xs font-semibold text-slate-800 sm:px-4 sm:py-3 sm:text-sm">
                    {{ $claim->reference_code ?? 'Pending approval' }}
                </p>

                <div class="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-2">
                    <div class="rounded-xl border border-slate-100 bg-white p-3 text-left">
                        <p class="text-[11px] font-semibold uppercase tracking-wider text-slate-400">
                            Approved Amount
                        </p>

                        <p class="mt-1 text-sm font-semibold text-slate-800">
                            ₱{{ number_format($claim->approved_amount ?? $claim->requested_amount, 2) }}
                        </p>
                    </div>

                    <div class="rounded-xl border border-slate-100 bg-white p-3 text-left">
                        <p class="text-[11px] font-semibold uppercase tracking-wider text-slate-400">
                            Expiration Date
                        </p>

                        <p class="mt-1 text-sm font-semibold text-slate-800">
                            {{ $claim->expiration_date?->format('M d, Y') ?? 'Not available' }}
                        </p>
                    </div>

                    <div class="rounded-xl border border-slate-100 bg-white p-3 text-left sm:col-span-2">
                        <p class="text-[11px] font-semibold uppercase tracking-wider text-slate-400">
                            Claim Status
                        </p>

                        <div class="mt-2 flex flex-wrap items-center gap-2">
                            <x-status-badge :status="$claimPassStatus" :tone="$claimPassStatus" size="xs" />

                            <span class="text-xs text-slate-500 sm:text-sm">
                                {{ $claim->is_claimed ? 'Already claimed at merchant' : ($claim->status === 'Approved' ? 'Ready for merchant validation' : $claim->status) }}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endif

<style>
@media print {
    aside,
    header,
    .print\:hidden {
        display: none !important;
    }

    body {
        background: white !important;
    }

    main {
        padding: 0 !important;
    }

    .print-pass {
        max-width: 720px !important;
        margin: 0 auto !important;
        padding: 32px !important;
        border: 1px solid #e2e8f0 !important;
        border-radius: 18px !important;
    }

    .print-pass * {
        box-shadow: none !important;
    }
}
</style>

<style>
    .qr-pass-frame svg {
        display: block;
        height: auto;
        max-width: min(100%, 220px);
    }

    @media (max-width: 420px) {
        .qr-pass-frame svg {
            max-width: min(100%, 190px);
        }
    }
</style>

@if($claim->qr_code)
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const modal = document.getElementById('qr-modal');
            const panel = document.getElementById('qr-modal-panel');
            const openButton = document.getElementById('open-qr-modal');
            const closeButton = document.getElementById('close-qr-modal');
            const backdrop = document.getElementById('qr-modal-backdrop');

            if (!modal || !panel || !openButton) {
                return;
            }

            const openModal = () => {
                modal.classList.remove('hidden');
                modal.classList.add('flex');

                requestAnimationFrame(() => {
                    panel.classList.remove('translate-y-3', 'scale-[0.98]', 'opacity-0');
                    panel.classList.add('translate-y-0', 'scale-100', 'opacity-100');
                });
            };

            const closeModal = () => {
                panel.classList.add('translate-y-3', 'scale-[0.98]', 'opacity-0');
                panel.classList.remove('translate-y-0', 'scale-100', 'opacity-100');

                window.setTimeout(() => {
                    modal.classList.add('hidden');
                    modal.classList.remove('flex');
                }, 180);
            };

            openButton.addEventListener('click', openModal);
            closeButton?.addEventListener('click', closeModal);
            backdrop?.addEventListener('click', closeModal);

            document.addEventListener('keydown', (event) => {
                if (event.key === 'Escape' && !modal.classList.contains('hidden')) {
                    closeModal();
                }
            });
        });
    </script>
@endif

@endsection
